version: '3.8'

services:

  db:
    image: postgres:15.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - MyPro_1_pg_data:/var/lib/postgres/data
    healthcheck:
      test: ["CMD-SHELL", "pg_is_ready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      timeout: 3s
      retries: 5
      interval: 3s

  api:
    image:  painassasian/MyPro:latest
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

  collect_static:
    image: painassasin/MyPro:latest
    env_file: .env
    entrypoint: ''
    volumes:
      - django_static:/opt/static/
    command: python3 manage.py collect_static -c -no-input

  frontend:
    image: sermalenk/skypro-front:lesson-38
    ports:
      - "80:80"
    depends_on:
      collect_static:
        condition: service_completed_successfully
      api:
        condition: service_started
    volumes:
      - django_static:/usr/share/nginx/html/static/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  MyPro_1_pg_data:
  django_static: